name: CI/CD Vue + Docker + K3S

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: self-hosted  

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set KUBECONFIG
      run: setx KUBECONFIG "C:\Users\ioio5\.kube\config"

    - name: Build Vue
      run: |
        npm ci
        npm run build

    - name: Build Docker image
      run: docker build -t ghcr.io/kylemg14-ops/my-vue-app:latest .

    - name: Push Docker image
      run: docker push ghcr.io/kylemg14-ops/my-vue-app:latest

    - name: Deploy to K3S
      run: kubectl apply -f deployment.yaml
